{{- if .Values.certificate.enabled -}}
# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# Source: iag5/templates/certificate.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "iag5.fullname" . }}-tls
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
  {{- with .Values.certificate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "iag5.fullname" . }}-tls-secret
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
    {{- if hasKey (.Values.certificate.issuer) "group" }}
    group: {{ .Values.certificate.issuer.group }}
    {{- end }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  duration: {{ .Values.certificate.duration }}
  commonName: {{ .Values.hostname }}
  {{- with .Values.certificate.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.certificate.ipAddresses .Values.certificate.includeServiceIPs }}
  ipAddresses:
  {{- range .Values.certificate.ipAddresses }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.certificate.includeServiceIPs }}
  {{- range .Values.certificate.services }}
    {{- if .clusterIP }}
    - {{ .clusterIP | quote }}
    {{- end }}
    {{- if .loadBalancerIP }}
    - {{ .loadBalancerIP | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.certificate.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.keystores }}
  keystores:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.certificate.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
